# Generated by Django 4.1.7 on 2023-04-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='market_source_data_ats',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('observation_date', models.DateTimeField()),
                ('publication_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('price_zone_code', models.IntegerField()),
                ('consumer_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('consumer_volume', models.DecimalField(decimal_places=6, max_digits=20)),
                ('thermal_volume', models.DecimalField(decimal_places=6, max_digits=20)),
                ('hydro_volume', models.DecimalField(decimal_places=6, max_digits=20)),
                ('atomic_volume', models.DecimalField(decimal_places=6, max_digits=20)),
                ('renewable_volume', models.DecimalField(decimal_places=6, max_digits=20)),
            ],
        ),
        migrations.AddIndex(
            model_name='market_source_data_ats',
            index=models.Index(fields=['observation_date'], name='ats_market__observa_92891c_idx'),
        ),
        migrations.AddIndex(
            model_name='market_source_data_ats',
            index=models.Index(fields=['price_zone_code'], name='ats_market__price_z_f2596a_idx'),
        ),
        migrations.AddConstraint(
            model_name='market_source_data_ats',
            constraint=models.UniqueConstraint(fields=('observation_date', 'price_zone_code'), name='unique-price-per-date-zone'),
        ),
    ]
